### ISSUE TITLE
compress сөзінің аудармасы

### ISSUE THREAD

**Issue by aishuak128** [son-of-Altay/eng-kk-tech-dictionary#1]
[General](https://github.com/son-of-Altay/eng-kk-tech-dictionary/blob/main/dictionary/general.md) парақшасында сіз **_compress_** сөзін **_сығу_** деп аударыпсыз. Дұрысы _**қысу**_ болады деп ойлаймын.

Мысалы: файлды қысу, қысу алгоритмы 

Кейде біртүрлі естілер, бірақ меніңше **_сығу_** деген сөз мүлде келіп тұрған жоқ. 
Мүмкін басқа бір сөз аударымын дәлірек жеткізер.

**Comment by son-of-Altay** [comment]
Ойланатын зат екен. 

Өз басым "сығу" сөзін қолдандым, өйткені compress аудармасы ретінде көп жерде қолданылып кеткен.

Тағы кісілердің пікірлерін күтейік (болса егер әрине).

**Comment by Ablay** [comment]
Жәй ұсыныс ретінде ықшамдау, нығыздау неген нұсқаларды де талқылап көрейік. Ықшамдау деген әдемі естілетін сияқты. Файлды ықшамдау, ықшамдау алгоритмы

**Comment by son-of-Altay** [comment]
@aishuak128 @Ablay @oitan @ardakshalkar @Saryarqa 

Әзірше "Сығу" сөзін @sab1tm -тің https://github.com/son-of-Altay/eng-kk-tech-dictionary/pull/4 PR-і арқылы келген "Қысу" аудармасына ауыстырдым.

Бірақ бұл сұрақ ашық күйі қала берсін. 

"Қысуға" ауыстырғанымызға келіспесеңіздер, айтыңыздар!
