### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Saryarqa** [son-of-Altay/eng-kk-tech-dictionary#7]
Нұсқаұлар
- Сұраныс
- Сұрау
- Сұрама

Сұрама деген сол нағыз Қазақ әдісімен жасалған сөз. Ежелгі Қазақ сөзді солай құрастырған

**Comment by Abu-Sagidolla** [comment]
сұрама күшті екен 
немесе сұрам

**Comment by son-of-Altay** [comment]
Маған да "Сұрама" мен @Abu-Sagidolla айтқан "сұрам" ұнап тұр.
